### ISSUE TITLE
[Connection failure?] Green doesn't work

### ISSUE THREAD

**Issue by IntinteDAO** [Blockstream/green_cli#15]
Hello, I'm aware that Liquid Green CLI is in the experimental phase, but there are some problems with establishing a connection with nod (but public). For example:

```
fervi@Osiris:~/green_cli$ green-liquid-cli --tor --network liquid set mnemonic ""
Nov 16 12:34:47.997 [notice] Tor 0.4.2.7 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Nov 16 12:34:47.997 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 16 12:34:47.997 [notice] Configuration file "/home/fervi/.torrc" not present, using reasonable defaults.
Nov 16 12:34:48.000 [notice] Opening Socks listener on 127.0.0.1:0
Nov 16 12:34:48.000 [notice] Socks listener listening on port 35637.
Nov 16 12:34:48.000 [notice] Opened Socks listener on 127.0.0.1:35637
Nov 16 12:34:48.000 [notice] Opening Control listener on 127.0.0.1:0
Nov 16 12:34:48.000 [notice] Control listener listening on port 39087.
Nov 16 12:34:48.000 [notice] Opened Control listener on 127.0.0.1:39087
Nov 16 12:34:48.000 [notice] Parsing GEOIP IPv4 file /home/fervi/gdk/build-clang/tor/build/share/tor/geoip.
Nov 16 12:34:48.000 [notice] Parsing GEOIP IPv6 file /home/fervi/gdk/build-clang/tor/build/share/tor/geoip6.
Nov 16 12:34:48.000 [notice] Bootstrapped 0% (starting): Starting
Nov 16 12:34:49.000 [notice] Starting with guard context "default"
Nov 16 12:34:49.000 [notice] New control connection opened from 127.0.0.1.
Nov 16 12:34:50.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Nov 16 12:34:50.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Nov 16 12:34:50.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Nov 16 12:34:51.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Nov 16 12:34:51.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Nov 16 12:34:51.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Nov 16 12:34:51.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Nov 16 12:34:51.000 [notice] Bootstrapped 100% (done): Done
Error: Invalid mnemonic
```

It's ok - wrong mnemonic (empty), but I execute this command again and:

```
fervi@Osiris:~/green_cli$ green-liquid-cli --tor --network liquid set mnemonic ""
Nov 16 12:35:18.030 [notice] Tor 0.4.2.7 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Nov 16 12:35:18.030 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 16 12:35:18.030 [notice] Configuration file "/home/fervi/.torrc" not present, using reasonable defaults.
Nov 16 12:35:18.032 [notice] Opening Socks listener on 127.0.0.1:0
Nov 16 12:35:18.032 [notice] Socks listener listening on port 33085.
Nov 16 12:35:18.032 [notice] Opened Socks listener on 127.0.0.1:33085
Nov 16 12:35:18.032 [notice] Opening Control listener on 127.0.0.1:0
Nov 16 12:35:18.032 [notice] Control listener listening on port 46439.
Nov 16 12:35:18.032 [notice] Opened Control listener on 127.0.0.1:46439
Nov 16 12:35:18.000 [notice] Parsing GEOIP IPv4 file /home/fervi/gdk/build-clang/tor/build/share/tor/geoip.
Nov 16 12:35:18.000 [notice] Parsing GEOIP IPv6 file /home/fervi/gdk/build-clang/tor/build/share/tor/geoip6.
Nov 16 12:35:18.000 [notice] Bootstrapped 0% (starting): Starting
Nov 16 12:35:19.000 [notice] Starting with guard context "default"
Nov 16 12:35:19.000 [notice] New control connection opened from 127.0.0.1.
Nov 16 12:35:20.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Nov 16 12:35:20.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Nov 16 12:35:20.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Nov 16 12:35:21.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Nov 16 12:35:21.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Nov 16 12:35:21.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Nov 16 12:35:21.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Nov 16 12:35:22.000 [notice] Bootstrapped 100% (done): Done
Traceback (most recent call last):
  File "/usr/local/bin/green-liquid-cli", line 8, in <module>
    sys.exit(main())
  File "/home/fervi/.local/lib/python3.8/site-packages/green_cli/green.py", line 687, in main
    green()
  File "/home/fervi/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/fervi/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/fervi/.local/lib/python3.8/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/fervi/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fervi/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/fervi/.local/lib/python3.8/site-packages/green_cli/green.py", line 211, in green
    session = Session({'name': network, 'use_tor': tor})
  File "/home/fervi/.local/lib/python3.8/site-packages/green_cli/green.py", line 173, in __init__
    super().__init__( net_params)
  File "/usr/local/lib/python3.8/dist-packages/greenaddress/__init__.py", line 370, in __init__
    return self.connect(net_params)
  File "/usr/local/lib/python3.8/dist-packages/greenaddress/__init__.py", line 407, in connect
    return connect(self.session_obj, self._to_json(net_params))
  File "/usr/local/lib/python3.8/dist-packages/greenaddress/__init__.py", line 95, in connect
    return libgreenaddress.connect(session, net_params)
RuntimeError: Failed
Nov 16 12:35:27.000 [notice] Catching signal TERM, exiting cleanly.
```

Why TOR? Cause it sometimes works (without never works). I wonder if I'm doing something wrong or if you can't use Green without your own node.

**Comment by jkauffman1** [comment]
Hi,
You're not doing anything wrong, except in the last case where you did not pass `--network liquid`. Passing `--network liquid` is necessary in all cases because by default it will try to use a local green network, which doesn't exist. Maybe the connection problem was just an intermittent issue? Does it happen repeatedly?

**Comment by IntinteDAO** [comment]
In general, I've had this problem for a few days, but I've been waiting for gdk to work on Python 3.8 to check on it (because I thought it might be a problem with Python 3.7).

In the meantime I almost synchronized the Liquid node, so you will be able to test if it works.

It's strange that the basic functions often don't work. Maybe my IP address is on the black list, but it does not go through TOR either.

Translated with www.DeepL.com/Translator (free version)
